name: Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: k8s-amd64
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build, test, and push the staging image
        uses: mattjmorrison-homelab/actions-k8s@2b3d79c6741b2bd80f02bb8672d0a6ad1b7fb4e9 # main
        with:
          service-account: app-backstage-job
          image: gcr.io/kaniko-project/executor@sha256:4e7a52dd1f14872430652bb3b027405b8dfd17c4538751c620ac005741ef9698
          shell: "false"
          command: >-
            --context=git://github.com/mattjmorrison-homelab/app-backstage.git#refs/heads/${{ github.head_ref }}
            --dockerfile=Dockerfile --skip-unused-stages=true --target=release
            --build-arg=COMMIT_SHA=${{ github.event.pull_request.head.sha }}
            --destination=registry.morrisons.site/app-backstage:pr-${{ github.event.pull_request.head.sha }}
            --snapshot-mode=redo --use-new-run=true
          secret-volume: app-backstage-zot-pull-secret:/kaniko/.docker
          active-deadline-seconds: "1800"
